name: action test-dev
on: [ push ]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.action}}"
      - run: echo "${{github.env}}"
      - run: echo "${{github.ref}}"
      - run: echo "${{github.repository}}"
